name: Keep Streamlit App Alive

on:
  schedule:
    # 10분마다 실행 (UTC 시간 기준)
    - cron: '*/10 * * * *'
  workflow_dispatch: # 수동 실행도 가능

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Streamlit App
      run: |
        echo "Pinging Streamlit app to keep it alive..."
        curl -f https://number-guessing100.streamlit.app/ || echo "Ping failed"
        echo "Ping completed at $(date)"
